 // User reducers
export const SET_USER_LOCATION = 'SET_USER_LOCATION'
export const SET_USER_COUNTRY = 'SET_USER_COUNTRY'
export const SET_USER = 'SET_USER'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const LOADING_USER = 'LOADING_USER'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'
export const LIKE_SCREAM = 'LIKE_SCREAM'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
 // UI reducers
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
 // Data reducers
export const LOADING_DATA = 'LOADING_DATA'
export const SET_ALERTS = 'SET_ALERTS' 
export const LIKE_ALERT = 'LIKE_ALERT' 
export const UNLIKE_ALERT = 'UNLIKE_ALERT' 
export const DELETE_ALERT = 'DELETE_ALERT'
export const POST_ALERT = 'POST_ALERT'
export const SET_ALERT = 'SET_ALERT'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'